### ISSUE TITLE
A similar project by me

### ISSUE THREAD

**Issue by UlyssesWu** [wangzexi/ZhiHuiShu-Assistant#3]
[**TalentChopper**](https://gitee.com/Ulysses/TalentChopper) is a similar project which I made several years ago (when I was a student), and I'm not sure if it still works.  
However, when it works you would just need to spend a few seconds on each lesson.

**Comment by wangzexi** [comment]
I think there is a great risk with this technology, may be easily judged as cheating...

**Comment by UlyssesWu** [comment]
In fact I never got banned or warned in my 2 yrs usage. And it's not that easy to be judged if you just set a suitable end time. When testing I tried to report that I have learned one lesson for 99999s but I'm still OK 😎 But of course, it can be made more safer by gradually increasing the progress without the video actually playing (and you can launching multiple tasks at the same time).

This not only save your time but also save your CPU / RAM / power / network traffic costs.
