### ISSUE TITLE
点击的随机延时可以换用正态曲线吗？

### ISSUE THREAD

**Issue by Zhang-Siyang** [wangzexi/ZhiHuiShu-Assistant#8]
当前的策略是0~60s随机取值，在统计上会表现起来不符合关于反应速度的曲线，所以我建议把`delay `用正态曲线生成，这样也不用再额外加上1s的延时了

**Comment by wangzexi** [comment]
目前的策略应该就不会被判作弊吧？
我认为「如无必要，勿增实体」。

**Comment by Zhang-Siyang** [comment]
但要是被查到了那就是不少同学的悲剧呢😥。您是作者，在程序复杂性和未来被坑可能性之间做个选择吧😀

**Comment by josark2005** [comment]
修改为`符合反应速度的曲线`没有必要，试验环境远没有真实环境来的复杂，不可能作为判断作弊的依据的。
